export const mockData = [
    {
      imageUrl: '/assets/images/pred01.jpeg',
      title: 'Luxury Downtown Apartment',
      location: 'New York, NY',
      tokenPrice: '100',
      annualYield: '8.5%',
      minInvestment: '1,000',
      progress: 65,
      totalTokens: 1000,
      availableTokens: 650,
    },
    {
      imageUrl: '/assets/images/pred3.jpg',
      title: 'Commercial Office Complex',
      location: 'Miami, FL',
      tokenPrice: '250',
      annualYield: '7.2%',
      minInvestment: '1,000',
      progress: 60,
      totalTokens: 2000,
      availableTokens: 1200,
    },
    {
        imageUrl: '/assets/images/pred4.jpg',
        title: 'Luxury Downtown Apartment',
        location: 'New York, NY',
        tokenPrice: '100',
        annualYield: '8.5%',
        minInvestment: '1,000',
        progress: 65,
        totalTokens: 1000,
        availableTokens: 650,
    },
    {
        imageUrl: '/assets/images/pred5.jpg',
        title: 'Luxury Downtown Apartment',
        location: 'New York, NY',
        tokenPrice: '100',
        annualYield: '8.5%',
        minInvestment: '1,000',
        progress: 65,
        totalTokens: 1000,
        availableTokens: 650,
    },
    {
      imageUrl: '/assets/images/pred01.jpeg',
      title: 'Luxury Downtown Apartment',
      location: 'New York, NY',
      tokenPrice: '100',
      annualYield: '8.5%',
      minInvestment: '1,000',
      progress: 65,
      totalTokens: 1000,
      availableTokens: 650,
    },
    {
      imageUrl: '/assets/images/pred3.jpg',
      title: 'Commercial Office Complex',
      location: 'Miami, FL',
      tokenPrice: '250',
      annualYield: '7.2%',
      minInvestment: '1,000',
      progress: 60,
      totalTokens: 2000,
      availableTokens: 1200,
    },
    {
        imageUrl: '/assets/images/pred4.jpg',
        title: 'Luxury Downtown Apartment',
        location: 'New York, NY',
        tokenPrice: '100',
        annualYield: '8.5%',
        minInvestment: '1,000',
        progress: 65,
        totalTokens: 1000,
        availableTokens: 650,
    },
    {
        imageUrl: '/assets/images/pred5.jpg',
        title: 'Luxury Downtown Apartment',
        location: 'New York, NY',
        tokenPrice: '100',
        annualYield: '8.5%',
        minInvestment: '1,000',
        progress: 65,
        totalTokens: 1000,
        availableTokens: 650,
    },
    {
      imageUrl: '/assets/images/pred01.jpeg',
      title: 'Luxury Downtown Apartment',
      location: 'New York, NY',
      tokenPrice: '100',
      annualYield: '8.5%',
      minInvestment: '1,000',
      progress: 65,
      totalTokens: 1000,
      availableTokens: 650,
    },
    {
      imageUrl: '/assets/images/pred3.jpg',
      title: 'Commercial Office Complex',
      location: 'Miami, FL',
      tokenPrice: '250',
      annualYield: '7.2%',
      minInvestment: '1,000',
      progress: 60,
      totalTokens: 2000,
      availableTokens: 1200,
    },
    {
        imageUrl: '/assets/images/pred4.jpg',
        title: 'Luxury Downtown Apartment',
        location: 'New York, NY',
        tokenPrice: '100',
        annualYield: '8.5%',
        minInvestment: '1,000',
        progress: 65,
        totalTokens: 1000,
        availableTokens: 650,
    },
    {
        imageUrl: '/assets/images/pred5.jpg',
        title: 'Luxury Downtown Apartment',
        location: 'New York, NY',
        tokenPrice: '100',
        annualYield: '8.5%',
        minInvestment: '1,000',
        progress: 65,
        totalTokens: 1000,
        availableTokens: 650,
    },
];